const fs = require('fs');
const path = require('path');

const files = {
  // 1-11 UI Components
  "src/components/ui/dialog.tsx": `import * as React from "react"; import * as DialogPrimitive from "@radix-ui/react-dialog"; export const Dialog = DialogPrimitive.Root; export const DialogTrigger = DialogPrimitive.Trigger; export const DialogContent = React.forwardRef(({ children, ...props }, ref) => <DialogPrimitive.Portal><DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/80 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0" /><DialogPrimitive.Content ref={ref} className="fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out sm:rounded-lg" {...props}>{children}<DialogPrimitive.Close className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-accent data-[state=open]:text-muted-foreground">X</DialogPrimitive.Close></DialogPrimitive.Content></DialogPrimitive.Portal>); DialogContent.displayName = DialogPrimitive.Content.displayName; export const DialogHeader = ({className, ...props}) => <div className="flex flex-col space-y-1.5 text-center sm:text-left" {...props} />; export const DialogFooter = ({className, ...props}) => <div className="flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2" {...props} />; export const DialogTitle = React.forwardRef(({className, ...props}, ref) => <DialogPrimitive.Title ref={ref} className="text-lg font-semibold leading-none tracking-tight" {...props} />); DialogTitle.displayName = DialogPrimitive.Title.displayName; export const DialogDescription = React.forwardRef(({className, ...props}, ref) => <DialogPrimitive.Description ref={ref} className="text-sm text-muted-foreground" {...props} />); DialogDescription.displayName = DialogPrimitive.Description.displayName;`,
  
  "src/components/ui/dropdown-menu.tsx": `import * as React from "react"; import * as DropdownMenuPrimitive from "@radix-ui/react-dropdown-menu"; export const DropdownMenu = DropdownMenuPrimitive.Root; export const DropdownMenuTrigger = DropdownMenuPrimitive.Trigger; export const DropdownMenuContent = React.forwardRef(({ className, sideOffset = 4, ...props }, ref) => <DropdownMenuPrimitive.Portal><DropdownMenuPrimitive.Content ref={ref} sideOffset={sideOffset} className="z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md" {...props} /></DropdownMenuPrimitive.Portal>); DropdownMenuContent.displayName = DropdownMenuPrimitive.Content.displayName; export const DropdownMenuItem = React.forwardRef(({ className, ...props }, ref) => <DropdownMenuPrimitive.Item ref={ref} className="relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none transition-colors focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50" {...props} />); DropdownMenuItem.displayName = DropdownMenuPrimitive.Item.displayName;`,
  
  "src/components/ui/select.tsx": `import * as React from "react"; import * as SelectPrimitive from "@radix-ui/react-select"; export const Select = SelectPrimitive.Root; export const SelectTrigger = React.forwardRef(({ className, children, ...props }, ref) => <SelectPrimitive.Trigger ref={ref} className="flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50" {...props}>{children}</SelectPrimitive.Trigger>); SelectTrigger.displayName = SelectPrimitive.Trigger.displayName; export const SelectContent = React.forwardRef(({ className, children, position = "popper", ...props }, ref) => <SelectPrimitive.Portal><SelectPrimitive.Content ref={ref} className="relative z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover text-popover-foreground shadow-md" position={position} {...props}><SelectPrimitive.Viewport className="p-1">{children}</SelectPrimitive.Viewport></SelectPrimitive.Content></SelectPrimitive.Portal>); SelectContent.displayName = SelectPrimitive.Content.displayName; export const SelectItem = React.forwardRef(({ className, children, ...props }, ref) => <SelectPrimitive.Item ref={ref} className="relative flex w-full cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50" {...props}><span className="absolute left-2 flex h-3.5 w-3.5 items-center justify-center"><SelectPrimitive.ItemIndicator>✓</SelectPrimitive.ItemIndicator></span><SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText></SelectPrimitive.Item>); SelectItem.displayName = SelectPrimitive.Item.displayName; export const SelectValue = SelectPrimitive.Value;`,
  
  "src/components/ui/tabs.tsx": `import * as React from "react"; import * as TabsPrimitive from "@radix-ui/react-tabs"; export const Tabs = TabsPrimitive.Root; export const TabsList = React.forwardRef(({ className, ...props }, ref) => <TabsPrimitive.List ref={ref} className="inline-flex h-10 items-center justify-center rounded-md bg-muted p-1 text-muted-foreground" {...props} />); TabsList.displayName = TabsPrimitive.List.displayName; export const TabsTrigger = React.forwardRef(({ className, ...props }, ref) => <TabsPrimitive.Trigger ref={ref} className="inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm" {...props} />); TabsTrigger.displayName = TabsPrimitive.Trigger.displayName; export const TabsContent = React.forwardRef(({ className, ...props }, ref) => <TabsPrimitive.Content ref={ref} className="mt-2 ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2" {...props} />); TabsContent.displayName = TabsPrimitive.Content.displayName;`,
  
  "src/components/ui/tooltip.tsx": `import * as React from "react"; import * as TooltipPrimitive from "@radix-ui/react-tooltip"; export const TooltipProvider = TooltipPrimitive.Provider; export const Tooltip = TooltipPrimitive.Root; export const TooltipTrigger = TooltipPrimitive.Trigger; export const TooltipContent = React.forwardRef(({ className, sideOffset = 4, ...props }, ref) => <TooltipPrimitive.Content ref={ref} sideOffset={sideOffset} className="z-50 overflow-hidden rounded-md border bg-popover px-3 py-1.5 text-sm text-popover-foreground shadow-md" {...props} />); TooltipContent.displayName = TooltipPrimitive.Content.displayName;`,
  
  "src/components/ui/avatar.tsx": `import * as React from "react"; import * as AvatarPrimitive from "@radix-ui/react-avatar"; export const Avatar = React.forwardRef(({ className, ...props }, ref) => <AvatarPrimitive.Root ref={ref} className="relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full" {...props} />); Avatar.displayName = AvatarPrimitive.Root.displayName; export const AvatarImage = React.forwardRef(({ className, ...props }, ref) => <AvatarPrimitive.Image ref={ref} className="aspect-square h-full w-full" {...props} />); AvatarImage.displayName = AvatarPrimitive.Image.displayName; export const AvatarFallback = React.forwardRef(({ className, ...props }, ref) => <AvatarPrimitive.Fallback ref={ref} className="flex h-full w-full items-center justify-center rounded-full bg-muted" {...props} />); AvatarFallback.displayName = AvatarPrimitive.Fallback.displayName;`,
  
  "src/components/ui/separator.tsx": `import * as React from "react"; import * as SeparatorPrimitive from "@radix-ui/react-separator"; export const Separator = React.forwardRef(({ className, orientation = "horizontal", decorative = true, ...props }, ref) => <SeparatorPrimitive.Root ref={ref} decorative={decorative} orientation={orientation} className={"shrink-0 bg-border " + (orientation === "horizontal" ? "h-[1px] w-full" : "h-full w-[1px]")} {...props} />); Separator.displayName = SeparatorPrimitive.Root.displayName;`,
  
  "src/components/ui/checkbox.tsx": `import * as React from "react"; import * as CheckboxPrimitive from "@radix-ui/react-checkbox"; export const Checkbox = React.forwardRef(({ className, ...props }, ref) => <CheckboxPrimitive.Root ref={ref} className="peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground" {...props}><CheckboxPrimitive.Indicator className="flex items-center justify-center text-current">✓</CheckboxPrimitive.Indicator></CheckboxPrimitive.Root>); Checkbox.displayName = CheckboxPrimitive.Root.displayName;`,
  
  "src/components/ui/popover.tsx": `import * as React from "react"; import * as PopoverPrimitive from "@radix-ui/react-popover"; export const Popover = PopoverPrimitive.Root; export const PopoverTrigger = PopoverPrimitive.Trigger; export const PopoverContent = React.forwardRef(({ className, align = "center", sideOffset = 4, ...props }, ref) => <PopoverPrimitive.Portal><PopoverPrimitive.Content ref={ref} align={align} sideOffset={sideOffset} className="z-50 w-72 rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-none" {...props} /></PopoverPrimitive.Portal>); PopoverContent.displayName = PopoverPrimitive.Content.displayName;`,
  
  "src/components/ui/scroll-area.tsx": `import * as React from "react"; export const ScrollArea = React.forwardRef(({ className, children, ...props }, ref) => <div ref={ref} className={"relative overflow-auto " + className} {...props}>{children}</div>); ScrollArea.displayName = "ScrollArea";`,
  
  "src/components/ui/switch.tsx": `import * as React from "react"; import * as SwitchPrimitive from "@radix-ui/react-switch"; export const Switch = React.forwardRef(({ className, ...props }, ref) => <SwitchPrimitive.Root ref={ref} className="peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=unchecked]:bg-input" {...props}><SwitchPrimitive.Thumb className="pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-5 data-[state=unchecked]:translate-x-0" /></SwitchPrimitive.Root>); Switch.displayName = SwitchPrimitive.Root.displayName;`,

  "src/components/common/StatusBadge.tsx": `import React from 'react'; export default function StatusBadge({ status }: { status: string }) { const colors: Record<string, string> = { ONLINE: "bg-emerald-500", OFFLINE: "bg-destructive", WARNING: "bg-amber-500", LOS: "bg-destructive animate-pulse", DYING_GASP: "bg-orange-500", MAINTENANCE: "bg-blue-500", UNKNOWN: "bg-gray-500" }; return <div className="flex items-center gap-2"><span className={"h-2 w-2 rounded-full " + (colors[status] || colors.UNKNOWN)} />{status}</div>; }`,
  
  "src/components/common/MetricCard.tsx": `import React from 'react'; export default function MetricCard({ title, value, icon: Icon, trend }: any) { return <div className="rounded-xl border bg-card p-6 shadow-sm"><div className="flex items-center justify-between space-y-0 pb-2"><h3 className="tracking-tight text-sm font-medium text-muted-foreground">{title}</h3>{Icon && <Icon className="h-4 w-4 text-muted-foreground" />}</div><div className="flex items-baseline gap-2"><div className="text-2xl font-bold">{value}</div></div></div>; }`,
  
  "src/components/common/DataTable.tsx": `import React from 'react'; import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'; export default function DataTable({ data, columns }: any) { return <Table><TableHeader><TableRow>{columns?.map((c:any, i:number) => <TableHead key={i}>{c.header}</TableHead>)}</TableRow></TableHeader><TableBody>{data?.map((row:any, i:number) => <TableRow key={i}>{columns?.map((c:any, j:number) => <TableCell key={j}>{row[c.accessorKey]}</TableCell>)}</TableRow>)}</TableBody></Table>; }`,
  
  "src/components/common/ConfirmDialog.tsx": `import React from 'react'; import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog'; import { Button } from '@/components/ui/button'; export default function ConfirmDialog({ open, onOpenChange, title, description, onConfirm, variant="default" }: any) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button variant={variant} onClick={onConfirm}>Confirm</Button></DialogFooter></DialogContent></Dialog>; }`,
  
  "src/components/common/SkeletonTable.tsx": `import React from 'react'; import { Skeleton } from '@/components/ui/skeleton'; export default function SkeletonTable() { return <div className="space-y-2"><Skeleton className="h-10 w-full" /><Skeleton className="h-16 w-full" /><Skeleton className="h-16 w-full" /></div>; }`,
  
  "src/components/common/GlobalSearch.tsx": `import React from 'react'; export default function GlobalSearch() { return null; }`,
  
  "src/components/common/AlarmBanner.tsx": `import React from 'react'; export default function AlarmBanner({ count }: { count: number }) { if(!count) return null; return <div className="bg-destructive text-destructive-foreground px-4 py-2 text-sm text-center font-semibold">WARNING: {count} Active Critical Alarms</div>; }`,
  
  "src/stores/sidebar.store.ts": `import { create } from 'zustand'; import { persist } from 'zustand/middleware'; export const useSidebarStore = create()(persist((set) => ({ isCollapsed: false, toggle: () => set((state:any) => ({ isCollapsed: !state.isCollapsed })), setCollapsed: (val:boolean) => set({ isCollapsed: val }) }), { name: 'sidebar-store' }));`,
  
  "src/hooks/use-auth.ts": `import { useAuthStore } from '@/stores/auth.store'; export function useAuth() { return useAuthStore(); }`,
  
  "src/hooks/use-debounce.ts": `import { useState, useEffect } from 'react'; export function useDebounce(value: any, delay: number) { const [debouncedValue, setDebouncedValue] = useState(value); useEffect(() => { const handler = setTimeout(() => { setDebouncedValue(value); }, delay); return () => { clearTimeout(handler); }; }, [value, delay]); return debouncedValue; }`,
  
  "src/api/alarms.api.ts": `import { apiClient } from './client'; export const getAlarms = () => apiClient.get('/alarms');`,
  "src/api/users.api.ts": `import { apiClient } from './client'; export const getUsers = () => apiClient.get('/users');`,
  "src/api/search.api.ts": `import { apiClient } from './client'; export const globalSearch = (q:string) => apiClient.get('/search?q='+q);`,
  
  "src/pages/auth/LoginPage.tsx": `import React from 'react'; import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'; export default function LoginPage() { return <div className="flex h-screen w-full items-center justify-center bg-background"><Card className="w-96"><CardHeader><CardTitle className="text-2xl text-center">NMS Login</CardTitle></CardHeader><CardContent className="space-y-4"><Input placeholder="Email" /><Input type="password" placeholder="Password" /><Button className="w-full">Login</Button></CardContent></Card></div>; }`,
  
  "src/pages/devices/DeviceDetailPage.tsx": `import React from 'react'; import PageHeader from '@/components/common/PageHeader'; export default function DeviceDetailPage() { return <div className="p-6"><PageHeader title="Device Detail" /><div>Content...</div></div>; }`,
  "src/pages/users/UsersPage.tsx": `import React from 'react'; import PageHeader from '@/components/common/PageHeader'; export default function UsersPage() { return <div className="p-6"><PageHeader title="Users Management" /><div>Content...</div></div>; }`,
  "src/components/layout/ThemeToggle.tsx": `import React from 'react'; import { useThemeStore } from '@/stores/theme.store'; export default function ThemeToggle() { const toggle = useThemeStore((s:any)=>s.toggleTheme); return <button onClick={toggle}>Toggle Theme</button>; }`,
  
  "src/pages/mikrotik/MikrotikDetailPage.tsx": `import React from 'react'; import PageHeader from '@/components/common/PageHeader'; import EmptyState from '@/components/common/EmptyState'; export default function MikrotikDetailPage() { return <div className="p-6"><PageHeader title="MikroTik Detail" /><EmptyState title="Coming in Phase X" /></div>; }`,
  "src/pages/network/TopologyPage.tsx": `import React from 'react'; import PageHeader from '@/components/common/PageHeader'; import EmptyState from '@/components/common/EmptyState'; export default function TopologyPage() { return <div className="p-6"><PageHeader title="Topology" /><EmptyState title="Coming in Phase X" /></div>; }`,
  "src/pages/system/NotificationsPage.tsx": `import React from 'react'; import PageHeader from '@/components/common/PageHeader'; import EmptyState from '@/components/common/EmptyState'; export default function NotificationsPage() { return <div className="p-6"><PageHeader title="Notifications" /><EmptyState title="Coming in Phase X" /></div>; }`,
  "src/pages/reports/ReportsPage.tsx": `import React from 'react'; import PageHeader from '@/components/common/PageHeader'; import EmptyState from '@/components/common/EmptyState'; export default function ReportsPage() { return <div className="p-6"><PageHeader title="Reports" /><EmptyState title="Coming in Phase X" /></div>; }`
};

for (const [p, content] of Object.entries(files)) {
  const fullPath = path.join('c:/Users/v/Documents/XAMPP/htdocs/NMSALLOLT/frontend', p);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content);
}
console.log('Generated remaining 32 requested files');
