export const POLLING_INTERVALS = {
  DEVICE_STATUS: 60000, // 1 minute
  ONU_METRICS: 300000, // 5 minutes
  TRAFFIC_STATS: 300000, // 5 minutes
};

export const SNMP_DEFAULTS = {
  VERSION: '2c',
  PORT: 161,
  TIMEOUT: 3000,
  RETRIES: 3,
  COMMUNITY_READ: 'public',
  COMMUNITY_WRITE: 'private'
};

export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 10,
  MAX_LIMIT: 100
};

export const ALARM_THRESHOLDS = {
  ONU_RX_POWER_WARNING_LOW: -25,
  ONU_RX_POWER_CRITICAL_LOW: -28,
  ONU_RX_POWER_WARNING_HIGH: -8,
  ONU_RX_POWER_CRITICAL_HIGH: -5,
  TEMPERATURE_WARNING: 65,
  TEMPERATURE_CRITICAL: 80
};
